# Generated by Django 5.2.6 on 2025-09-05 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.TextField(verbose_name="Место")),
                (
                    "time_processing",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Время, сек."
                    ),
                ),
                ("action", models.TextField(verbose_name="Действие")),
                ("is_pleasant", models.BooleanField(verbose_name="Приятная привычка")),
                (
                    "period",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Частота выполнения привычки"
                    ),
                ),
                ("reward", models.TextField(verbose_name="Вознаграждение")),
                (
                    "max_time_processing",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Максимальное время на выполнение"
                    ),
                ),
                ("is_publik", models.BooleanField(verbose_name="Признак публичности")),
                (
                    "fk_habits",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habits",
                        verbose_name="ссылка на приятную привычку",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
